networks:
  laravel:
    name: laravel
services:
  php:
    build:
      context: ./php
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel
  mysql:
    image: mysql:9.4.0
    container_name: mysql
    ports:
      - 4306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravelDB
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT: secret
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - laravel

  nginx:
    build:
      context: ./nginx
      dockerfile: nginx.dockerfile
    container_name: nginx
    depends_on:
      - php
      - mysql
    ports:
      - 80:80
      - 433:433
    volumes:
      - ./src:/var/www/html
      # - ./src:/usr/share/nginx/html
    networks:
      - laravel
  # apache:
  #   build:
  #     context: ./apache
  #     dockerfile: apache.dockerfile
  #   image: httpd:2.4.65-alpine
  #   container_name: apache
  #   ports:
  #     - 80:80
  #     - 433:433
  #   volumes:
  #     - ./src:/var/www/html
  #   networks:
  #     - laravel

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel
    


